wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699927457.679726
    t:
      1:
      - 1
      - 2
      - 3
      - 9
      - 12
      - 41
      - 50
      - 55
      - 103
      2:
      - 1
      - 2
      - 3
      - 9
      - 12
      - 41
      - 50
      - 55
      - 103
      3:
      - 1
      - 2
      - 13
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 1
      - 8
      - 12
      13: linux-x86_64
base:
  desc: null
  value:
    max_epochs: 25
    use_cuda: true
    num_threads: 1
    log_every_n_steps: 1
    profiler: null
    base_dir: default
    seed: None
logger:
  desc: null
  value:
    type: wandb
    offline: false
    project: adroit_door
    entity: qhershey
    name: experiment
    console_level: info
    sample_data_size: 2
    log_model: true
    save_model: true
    save_model_name: final.pt
    run_path_file: wandb_path.json
model:
  desc: null
  value:
    factory_type: callbacks
    model_type: description
    name: description_sparse
    learning_rate: 0.0001
    row_sizes:
    - 39
    - 300
    - 28
    col_sizes:
    - 39
    - 300
    - 28
    bias: true
    block_types:
    - - 0
      - 0
      - 0
    - - R=0.20
      - R=0.20
      - R=0.20
    - - R=0.20
      - R=0.20
      - R=0.20
    initialization_types:
    - - 0
      - 0
      - 0
    - - G=0,0.05
      - G=0,0.05
      - G=0,0.05
    - - G=0,0.05
      - G=0,0.05
      - G=0,0.05
    trainable:
    - - false
      - false
      - false
    - - non-zero
      - non-zero
      - non-zero
    - - non-zero
      - non-zero
      - non-zero
    activations:
    - Identity
    - ReLU
    - Identity
    activation_sizes:
    - 39
    - 300
    - 28
    callbacks:
      loss:
        func: MSELoss
        idx_list: asteval::range(39+300, 39+300+28)
        sequence_position: last
      initialization:
        func: zeros
        size: asteval::39+300+28
      data:
        func: insert
        idx_list: asteval::range(39)
        flatten_input: true
      output:
        func: max
        idx_list: asteval::range(39+300, 39+300+28)
data:
  desc: null
  value:
    dataset: adroit_door
    name: adroit_door
    train_size: 4500
    validation_size: 250
    test_size: 250
    batch_size: 64
available:
  desc: null
  value: true
current_device:
  desc: null
  value: 0
device:
  desc: null
  value: <torch.cuda.device object at 0x797b0f34c640>
device_count:
  desc: null
  value: 1
device_name:
  desc: null
  value: Tesla T4
total_parameters:
  desc: null
  value: 24363
