factory_type: callbacks
model_type: LSTM
name: LSTM
learning_rate: 1e-4

input_size: 46
hidden_size: 3727
output_size: 26

activations: False

callbacks:
    loss: 
        func: MSELoss
        idx_list: "asteval::range(46+3727, 46+3727+26)"
        sequence_position: last
    initialization:
        func: zeros
        size: "asteval::46+3727+26"
    data: 
        func: insert
        idx_list: "asteval::range(46)"
        flatten_input: True
    output: 
        func: all
        idx_list: "asteval::range(46+3727, 46+3727+26)"
