factory_type: callbacks
model_type: description
name: description_sparse
learning_rate: 1e-4

row_sizes:
  - 71
  - 118
  - 9
col_sizes:
  - 71
  - 118
  - 9
bias: True

block_types:
  - [0, 0, 0]
  - [R=1.00, R=1.00, R=1.00]
  - [R=1.00, R=1.00, R=1.00]
initialization_types:
  - [0, 0, 0]
  - ["G=0,0.05", "G=0,0.05", "G=0,0.05"]
  - ["G=0,0.05", "G=0,0.05", "G=0,0.05"]
trainable:
  - [False, False, False]
  - ['non-zero', 'non-zero', 'non-zero']
  - ['non-zero', 'non-zero', 'non-zero']

activations:
  - Identity
  - ReLU
  - Identity

activation_sizes:
  - 71
  - 118
  - 9

callbacks:
    loss: 
        func: MSELoss
        idx_list: "asteval::range(71+118, 71+118+9)"
        sequence_position: last
    initialization:
        func: zeros
        size: "asteval::71+118+9"
    data: 
        func: insert
        idx_list: "asteval::range(71)"
        flatten_input: True
    output: 
        func: all
        idx_list: "asteval::range(71+118, 71+118+9)"
