factory_type: callbacks
model_type: LSTM
name: LSTM
learning_rate: 1e-4

input_size: 71
hidden_size: 2671
output_size: 9

activations: False

callbacks:
    loss: 
        func: MSELoss
        idx_list: "asteval::range(71+2671, 71+2671+9)"
        sequence_position: last
    initialization:
        func: zeros
        size: "asteval::71+2671+9"
    data: 
        func: insert
        idx_list: "asteval::range(71)"
        flatten_input: True
    output: 
        func: all
        idx_list: "asteval::range(71+2671, 71+2671+9)"
