factory_type: callbacks
model_type: LSTM
name: LSTM
learning_rate: 1e-4

input_size: 81
hidden_size: 1326
output_size: 9

activations: False

callbacks:
    loss: 
        func: MSELoss
        idx_list: "asteval::range(81+1326, 81+1326+9)"
        sequence_position: last
    initialization:
        func: zeros
        size: "asteval::81+1326+9"
    data: 
        func: insert
        idx_list: "asteval::range(81)"
        flatten_input: True
    output: 
        func: all
        idx_list: "asteval::range(81+1326, 81+1326+9)"
