factory_type: callbacks
model_type: LSTM
name: LSTM
structure: lstm
learning_rate: 1e-4

input_size: 46
hidden_size: 31
output_size: 26

activations: False

callbacks:
    loss: 
        func: MSELoss
        idx_list: "asteval::range(46+31, 46+31+26)"
        sequence_position: last
    initialization:
        func: zeros
        size: "asteval::46+31+26"
    data: 
        func: insert
        idx_list: "asteval::range(46)"
        flatten_input: True
    output: 
        func: all
        idx_list: "asteval::range(46+31, 46+31+26)"
